/**
 * CSV Exporter for GEO Audit Reports
 * Exports complete AuditResult data as RFC 4180 compliant CSV
 * 
 * RFC 4180 Compliance:
 * - Fields containing commas, quotes, or newlines are enclosed in double quotes
 * - Double quotes within fields are escaped by doubling them ("")
 * - Consistent column structure across all exports
 * - UTF-8 encoding for Unicode support
 */

import { AuditResult } from '../../geoAuditEnhanced';
import { 
  ExportFormat, 
  ExportOutput, 
  ExportMetadata, 
  FormatExporter,
  ExportOptions
} from '../types';
import { ExportSecurity } from '../security';
import { getExportMetadata } from '../metadata';

export class CSVExporter implements FormatExporter {
  readonly format = ExportFormat.CSV;
  
  /**
   * Export AuditResult to CSV format
   * Includes all fields with proper RFC 4180 escaping
   */
  async export(result: AuditResult, options?: ExportOptions): Promise<ExportOutput> {
    // Report progress if callback provided
    options?.progressCallback?.(60, 'Generating CSV rows...');
    
    // Get standardized metadata (Requirements 6.1, 6.2, 6.3)
    const metadata = getExportMetadata(ExportFormat.CSV);
    
    const rows: string[][] = [];
    
    // ===== HEADER SECTION (Requirements 6.1-6.3) =====
    rows.push(['GEO Audit Report - CSV Export']);
    rows.push(['Generated By', metadata.generatedBy]);
    rows.push(['Generated At', metadata.generatedAt]);
    rows.push(['Tool Version', metadata.toolVersion]);
    rows.push(['Export Version', metadata.exportVersion]);
    rows.push([]);
    
    // ===== METADATA SECTION =====
    rows.push(['Website Metadata']);
    rows.push(['Field', 'Value']);
    rows.push(['Website', new URL(result.url).hostname]);
    rows.push(['URL', result.url]);
    rows.push(['Analysis Date', new Date(result.timestamp).toLocaleString()]);
    rows.push(['Timestamp (ISO 8601)', result.timestamp]);
    rows.push(['Overall Score', String(result.overallScore)]);
    rows.push(['Precise Score', String(result.preciseScore)]);
    rows.push(['Grade', result.grade]);
    
    // Score breakdown if available
    if (result.scoreBreakdown) {
      rows.push(['Core Score', String(result.scoreBreakdown.core || '')]);
      rows.push(['Technical Score', String(result.scoreBreakdown.technical || '')]);
      rows.push(['Content Score', String(result.scoreBreakdown.content || '')]);
      rows.push(['Weighted Score', String(result.scoreBreakdown.weighted || '')]);
    }
    
    rows.push([]);
    
    // ===== SCORE BREAKDOWN SECTION =====
    rows.push(['Score Breakdown']);
    rows.push(['Category', 'Score', 'Status']);
    
    const scoreEntries: [string, number][] = [
      ['Schema Markup', result.scores.schemaMarkup],
      ['Meta Tags', result.scores.metaTags],
      ['AI Crawlers', result.scores.aiCrawlers],
      ['E-E-A-T', result.scores.eeat],
      ['Structure', result.scores.structure],
      ['Performance', result.scores.performance],
      ['Content Quality', result.scores.contentQuality],
      ['Citation Potential', result.scores.citationPotential],
      ['Technical SEO', result.scores.technicalSEO],
      ['Link Analysis', result.scores.linkAnalysis],
      ['AID Agent', result.scores.aidAgent]
    ];
    
    scoreEntries.forEach(([categoryName, score]) => {
      const status = this.getScoreStatus(score);
      rows.push([categoryName, String(score), status]);
    });
    
    rows.push([]);
    
    // ===== DETAILED STATISTICS SECTION =====
    rows.push(['Detailed Statistics']);
    rows.push(['Category', 'Metric', 'Value']);
    
    // Schema markup stats
    if (result.details.schemaMarkup) {
      const sm = result.details.schemaMarkup;
      rows.push(['Schema Markup', 'Total Schemas', String(sm.totalSchemas || 0)]);
      rows.push(['Schema Markup', 'Valid Schemas', String(sm.validSchemas || 0)]);
      rows.push(['Schema Markup', 'Has Graph Structure', String(sm.hasGraphStructure || false)]);
      // List which schema types are present
      const presentSchemas = Object.entries(sm.schemas)
        .filter(([_, present]) => present)
        .map(([type, _]) => type);
      if (presentSchemas.length > 0) {
        rows.push(['Schema Markup', 'Schema Types', presentSchemas.join('; ')]);
      }
    }
    
    // Meta tags stats
    if (result.details.metaTags) {
      const mt = result.details.metaTags;
      rows.push(['Meta Tags', 'Has Title', String(mt.hasTitle || false)]);
      rows.push(['Meta Tags', 'Has Description', String(mt.hasDescription || false)]);
      rows.push(['Meta Tags', 'Has OG Tags', String(mt.hasOGTags || false)]);
      rows.push(['Meta Tags', 'Has Twitter Card', String(mt.hasTwitterCard || false)]);
    }
    
    // AI Crawlers stats
    if (result.details.aiCrawlers) {
      const ac = result.details.aiCrawlers;
      rows.push(['AI Crawlers', 'Total AI Crawlers', String(ac.totalAICrawlers || 0)]);
      rows.push(['AI Crawlers', 'Robots.txt Found', String(ac.robotsTxtFound || false)]);
      rows.push(['AI Crawlers', 'Has Sitemap', String(ac.hasSitemap || false)]);
      rows.push(['AI Crawlers', 'Allows GPTBot', String(ac.allowsGPTBot || false)]);
      rows.push(['AI Crawlers', 'Allows Claude', String(ac.allowsClaude || false)]);
      rows.push(['AI Crawlers', 'Allows Perplexity', String(ac.allowsPerplexity || false)]);
    }
    
    // Content quality stats
    if (result.details.contentQuality) {
      const cq = result.details.contentQuality;
      rows.push(['Content Quality', 'Word Count', String(cq.wordCount || 0)]);
      rows.push(['Content Quality', 'Readability Score', String(cq.readabilityScore || 0)]);
      rows.push(['Content Quality', 'AI Readability Score', String(cq.aiReadabilityScore || 0)]);
      rows.push(['Content Quality', 'Paragraph Count', String(cq.paragraphCount || 0)]);
      rows.push(['Content Quality', 'Image Count', String(cq.imageCount || 0)]);
      rows.push(['Content Quality', 'Video Count', String(cq.videoCount || 0)]);
      rows.push(['Content Quality', 'Has Lists', String(cq.hasLists || false)]);
      rows.push(['Content Quality', 'Has Tables', String(cq.hasTables || false)]);
      rows.push(['Content Quality', 'Content Depth', cq.contentDepth || 'unknown']);
    }
    
    // Performance stats
    if (result.details.performance) {
      const perf = result.details.performance;
      rows.push(['Performance', 'HTML Size (bytes)', String(perf.htmlSize || 0)]);
      rows.push(['Performance', 'External Scripts', String(perf.externalScripts || 0)]);
      rows.push(['Performance', 'External Styles', String(perf.externalStyles || 0)]);
      rows.push(['Performance', 'Images', String(perf.images || 0)]);
      rows.push(['Performance', 'Total Resources', String(perf.totalResources || 0)]);
      rows.push(['Performance', 'Has Lazy Loading', String(perf.hasLazyLoading || false)]);
    }
    
    // Link analysis stats
    if (result.details.linkAnalysis) {
      const la = result.details.linkAnalysis;
      rows.push(['Link Analysis', 'Total Links', String(la.totalLinks || 0)]);
      rows.push(['Link Analysis', 'Internal Links', String(la.internalLinks || 0)]);
      rows.push(['Link Analysis', 'External Links', String(la.externalLinks || 0)]);
      rows.push(['Link Analysis', 'Nofollow Ratio', String(la.nofollowRatio || 0)]);
      rows.push(['Link Analysis', 'Broken Links', String(la.brokenLinks || 0)]);
    }
    
    // Citation potential stats
    if (result.details.citationPotential) {
      const cp = result.details.citationPotential;
      rows.push(['Citation Potential', 'Score', String(cp.score || 0)]);
      rows.push(['Citation Potential', 'Factual Statements', String(cp.factualStatements || 0)]);
      rows.push(['Citation Potential', 'Data Points', String(cp.dataPoints || 0)]);
      rows.push(['Citation Potential', 'Quotes', String(cp.quotes || 0)]);
      rows.push(['Citation Potential', 'References', String(cp.references || 0)]);
      rows.push(['Citation Potential', 'Definitions', String(cp.definitions || 0)]);
      if (cp.sourceQuality) {
        rows.push(['Citation Potential', 'Source Quality Score', String(cp.sourceQuality.qualityScore || 0)]);
        rows.push(['Citation Potential', 'Total Sources', String(cp.sourceQuality.totalSources || 0)]);
      }
    }
    
    // Technical SEO stats
    if (result.details.technicalSEO) {
      const ts = result.details.technicalSEO;
      rows.push(['Technical SEO', 'Has Sitemap XML', String(ts.hasSitemapXML || false)]);
      rows.push(['Technical SEO', 'Sitemap Accessible', String(ts.sitemapAccessible || false)]);
      rows.push(['Technical SEO', 'Has Robots.txt', String(ts.hasRobotsTxt || false)]);
      rows.push(['Technical SEO', 'Is HTTPS', String(ts.isHTTPS || false)]);
      rows.push(['Technical SEO', 'Has Security Headers', String(ts.hasSecurityHeaders || false)]);
      rows.push(['Technical SEO', 'Has Canonical', String(ts.hasCanonical || false)]);
      rows.push(['Technical SEO', 'HTTP Status', String(ts.httpStatus || 'unknown')]);
    }
    
    // E-E-A-T stats
    if (result.details.eeat) {
      const eeat = result.details.eeat;
      rows.push(['E-E-A-T', 'Author Info Present', String(eeat.hasAuthorInfo || false)]);
      rows.push(['E-E-A-T', 'Credentials Present', String(eeat.hasCredentials || false)]);
      rows.push(['E-E-A-T', 'Contact Info Present', String(eeat.hasContactInfo || false)]);
    }
    
    // Structure stats
    if (result.details.structure) {
      const struct = result.details.structure;
      rows.push(['Structure', 'Has H1', String(struct.hasH1 || false)]);
      rows.push(['Structure', 'H1 Count', String(struct.h1Count || 0)]);
      rows.push(['Structure', 'Has Semantic HTML', String(struct.hasSemanticHTML || false)]);
      rows.push(['Structure', 'Heading Hierarchy', String(struct.headingHierarchy || false)]);
      rows.push(['Structure', 'Has Nav', String(struct.hasNav || false)]);
      rows.push(['Structure', 'Has Main', String(struct.hasMain || false)]);
      rows.push(['Structure', 'Has Footer', String(struct.hasFooter || false)]);
    }
    
    // AID Agent stats
    if (result.details.aidAgent) {
      const aid = result.details.aidAgent;
      rows.push(['AID Agent', 'Detected', String(aid.detected || false)]);
      rows.push(['AID Agent', 'Discovery Method', aid.discoveryMethod || 'none']);
      rows.push(['AID Agent', 'Agent Name', aid.agentName || '']);
      rows.push(['AID Agent', 'Agent Version', aid.agentVersion || '']);
      rows.push(['AID Agent', 'Endpoint', aid.endpoint || '']);
    }
    
    rows.push([]);
    
    // ===== RECOMMENDATIONS SECTION =====
    rows.push(['Recommendations']);
    rows.push(['Priority', 'Effort', 'Category', 'Title', 'Description', 'Impact', 'Implementation', 'Estimated Time']);
    
    result.recommendations.forEach(rec => {
      rows.push([
        rec.priority || '',
        rec.effort || '',
        rec.category || '',
        rec.title || '',
        rec.description || '',
        rec.impact || '',
        rec.implementation || '',
        rec.estimatedTime || ''
      ]);
    });
    
    rows.push([]);
    
    // ===== INSIGHTS SECTION =====
    if (result.insights && result.insights.length > 0) {
      rows.push(['Key Insights']);
      rows.push(['Insight Number', 'Insight']);
      result.insights.forEach((insight, index) => {
        rows.push([String(index + 1), insight]);
      });
      rows.push([]);
    }
    
    // ===== KNOWLEDGE GRAPH SECTION (if present) =====
    if (result.knowledgeGraph) {
      rows.push(['Knowledge Graph']);
      rows.push(['Metric', 'Value']);
      rows.push(['Entity Count', String(result.knowledgeGraph.entities?.length || 0)]);
      rows.push(['Relationship Count', String(result.knowledgeGraph.relationships?.length || 0)]);
      rows.push(['Claim Count', String(result.knowledgeGraph.claims?.length || 0)]);
      
      // Export entities if present
      if (result.knowledgeGraph.entities && result.knowledgeGraph.entities.length > 0) {
        rows.push([]);
        rows.push(['Knowledge Graph Entities']);
        rows.push(['Entity ID', 'Type', 'Name', 'Description', 'URL']);
        result.knowledgeGraph.entities.forEach(entity => {
          rows.push([
            entity.id || '',
            entity.type || '',
            entity.name || '',
            entity.description || '',
            entity.url || ''
          ]);
        });
      }
      
      rows.push([]);
    }
    
    // ===== BROWSER METADATA SECTION (if present) =====
    if (result.browserMetadata) {
      rows.push(['Browser Metadata']);
      rows.push(['Field', 'Value']);
      rows.push(['Used Browser', String(result.browserMetadata.usedBrowser || false)]);
      rows.push(['User Agent', result.browserMetadata.userAgent || '']);
      if (result.browserMetadata.viewport) {
        rows.push(['Viewport Width', String(result.browserMetadata.viewport.width || 0)]);
        rows.push(['Viewport Height', String(result.browserMetadata.viewport.height || 0)]);
      }
      rows.push(['Final URL', result.browserMetadata.finalUrl || '']);
      rows.push(['Load Time (ms)', String(result.browserMetadata.loadTime || 0)]);
      rows.push([]);
    }
    
    // Convert rows to CSV string with proper RFC 4180 escaping
    const csvContent = rows
      .map(row => row.map(cell => ExportSecurity.escapeCSV(cell)).join(','))
      .join('\n');
    
    // Generate safe filename
    const hostname = new URL(result.url).hostname;
    const timestamp = Date.now();
    const filename = ExportSecurity.sanitizeFilename(
      `GEO-Audit-${hostname}-${timestamp}.csv`
    );
    
    return {
      content: csvContent,
      filename,
      mimeType: 'text/csv;charset=utf-8',
      size: new Blob([csvContent]).size
    };
  }
  
  /**
   * Validate CSV output
   * Ensures the output is valid CSV with required sections
   */
  validate(output: string | Uint8Array): boolean {
    try {
      if (typeof output !== 'string') {
        return false;
      }
      
      // Basic CSV validation
      const lines = output.split('\n');
      if (lines.length < 10) {
        return false; // Too few lines for a complete export
      }
      
      // Check for required sections
      const hasHeader = output.includes('GEO Audit Report - CSV Export');
      const hasMetadata = output.includes('Website Metadata');
      const hasScoreBreakdown = output.includes('Score Breakdown');
      const hasRecommendations = output.includes('Recommendations');
      
      // Verify all 11 score categories are present
      const requiredCategories = [
        'Schema Markup',
        'Meta Tags',
        'AI Crawlers',
        'E-E-A-T',
        'Structure',
        'Performance',
        'Content Quality',
        'Citation Potential',
        'Technical SEO',
        'Link Analysis',
        'AID Agent'
      ];
      
      const allCategoriesPresent = requiredCategories.every(category => 
        output.includes(category)
      );
      
      return hasHeader && hasMetadata && hasScoreBreakdown && 
             hasRecommendations && allCategoriesPresent;
    } catch {
      return false;
    }
  }
  
  /**
   * Get metadata about CSV export format
   */
  getMetadata(): ExportMetadata {
    return {
      format: ExportFormat.CSV,
      specification: 'RFC 4180',
      mimeType: 'text/csv',
      fileExtension: '.csv',
      supportsStreaming: true,
      maxRecommendedSize: 10 * 1024 * 1024 // 10 MB
    };
  }
  
  /**
   * Get human-readable status for a score
   */
  private getScoreStatus(score: number): string {
    if (score >= 80) return 'Excellent';
    if (score >= 60) return 'Good';
    if (score >= 40) return 'Fair';
    return 'Needs Improvement';
  }
}
