/**
 * Plain Text Exporter - Exports audit results to plain text format
 */

import { AuditResult } from '../../geoAuditEnhanced';
import { ExportFormat, ExportOutput, ExportMetadata, FormatExporter, ExportOptions } from '../types';
import { ExportSecurity } from '../security';

export class PlainTextExporter implements FormatExporter {
  readonly format = ExportFormat.PLAIN_TEXT;
  
  async export(result: AuditResult, options?: ExportOptions): Promise<ExportOutput> {
    // Generate plain text content
    const text = this.generatePlainText(result);
    
    // Generate filename
    const hostname = new URL(result.url).hostname;
    const timestamp = Date.now();
    const filename = ExportSecurity.sanitizeFilename(`geo-audit-${hostname}-${timestamp}.txt`);
    
    return {
      content: text,
      filename,
      mimeType: 'text/plain',
      size: new Blob([text]).size
    };
  }
  
  validate(output: string | Uint8Array): boolean {
    if (typeof output !== 'string') return false;
    return output.length > 0;
  }
  
  getMetadata(): ExportMetadata {
    return {
      format: ExportFormat.PLAIN_TEXT,
      specification: 'UTF-8 Plain Text',
      mimeType: 'text/plain',
      fileExtension: '.txt',
      supportsStreaming: true,
      maxRecommendedSize: 5 * 1024 * 1024 // 5MB
    };
  }
  
  private generatePlainText(result: AuditResult): string {
    const lines: string[] = [];
    
    lines.push('═══════════════════════════════════════════════════════════');
    lines.push('                    GEO AUDIT REPORT                      ');
    lines.push('═══════════════════════════════════════════════════════════');
    lines.push('');
    lines.push(`URL: ${result.url}`);
    lines.push(`Date: ${new Date(result.timestamp).toLocaleString()}`);
    lines.push(`Grade: ${result.grade}`);
    lines.push(`Overall Score: ${result.preciseScore.toFixed(3)} / 100`);
    lines.push('');
    lines.push('───────────────────────────────────────────────────────────');
    lines.push('CATEGORY SCORES');
    lines.push('───────────────────────────────────────────────────────────');
    lines.push('');
    
    Object.entries(result.scores).forEach(([key, value]) => {
      lines.push(`${key.padEnd(25)} ${value.toFixed(1).padStart(6)}`);
    });
    
    lines.push('');
    lines.push('───────────────────────────────────────────────────────────');
    lines.push('TOP RECOMMENDATIONS');
    lines.push('───────────────────────────────────────────────────────────');
    lines.push('');
    
    result.recommendations.slice(0, 10).forEach((rec, idx) => {
      lines.push(`${idx + 1}. ${rec.title}`);
      lines.push(`   Priority: ${rec.priority.toUpperCase()}`);
      lines.push(`   ${rec.description}`);
      lines.push('');
    });
    
    lines.push('═══════════════════════════════════════════════════════════');
    lines.push('Generated by Anóteros Lógos GEO Audit Engine');
    lines.push('═══════════════════════════════════════════════════════════');
    
    return lines.join('\n');
  }
}
