/**
 * Citation Intelligence Types
 * TypeScript interfaces for the Predictive Citation Intelligence Engine
 * 
 * This module defines all core data models for citation prediction,
 * content optimization, knowledge graph analysis, and temporal forecasting.
 */

import { Json } from './database.types';

// ============================================================================
// Core Result Types
// ============================================================================

/**
 * Result of citation probability calculation
 * Represents the likelihood (0-100) that AI systems will cite specific content
 */
export interface CitationProbabilityResult {
  /** Citation probability score (0-100) */
  score: number;
  
  /** Confidence interval for the score */
  confidence: {
    lower: number;
    upper: number;
  };
  
  /** Factors contributing to the score */
  factors: {
    name: string;
    contribution: number; // -100 to +100
    description: string;
  }[];
  
  /** Quick-win opportunities for improvement */
  quickWins: {
    action: string;
    expectedLift: number;
    effort: 'low' | 'medium' | 'high';
  }[];
}

/**
 * Temporal forecast result
 * Predictions for future citation performance
 */
export interface ForecastResult {
  /** Forecasts for different time horizons */
  horizons: {
    days: 30 | 60 | 90;
    predicted: number;
    confidence: { lower: number; upper: number };
    drivers: string[];
  }[];
  
  /** Rate of change in citation frequency (citations per day) */
  citationVelocity: number;
  
  /** Seasonal patterns affecting citations */
  seasonalFactors: {
    month: number;
    multiplier: number;
  }[];
}

/**
 * Content variation generated by optimization engine
 * Represents an optimized version of original content
 */
export interface ContentVariation {
  /** Unique identifier for this variation */
  id: string;
  
  /** Optimized content text */
  content: string;
  
  /** Predicted citation probability score */
  predictedScore: number;
  
  /** Metrics showing improvement over original */
  improvements: {
    semanticDensity: number; // % increase
    entityCount: number;
    claimStrength: number;
  };
  
  /** Detailed changes made to content */
  changes: {
    type: 'addition' | 'modification' | 'restructure';
    location: string;
    description: string;
  }[];
  
  /** Implementation guidance */
  implementation: {
    html: string;
    schema: Json;
    structural: string[];
  };
}

/**
 * Entity authority score
 * Measures an entity's credibility and citation-worthiness
 */
export interface EntityAuthority {
  /** Entity identifier */
  entityId: string;
  
  /** Entity name */
  entityName: string;
  
  /** Entity type (Person, Organization, etc.) */
  entityType: EntityType;
  
  /** Overall authority score (0-100) */
  authorityScore: number;
  
  /** Component scores */
  components: {
    relationshipDensity: number;
    claimEvidence: number;
    externalValidation: number;
    temporalConsistency: number;
  };
  
  /** Competitive ranking */
  competitiveRanking: {
    percentile: number;
    topCompetitors: {
      name: string;
      score: number;
    }[];
  };
  
  /** Growth trend */
  growthTrend: {
    direction: 'increasing' | 'decreasing' | 'stable';
    velocity: number;
  };
}

/**
 * Temporal data point
 * Historical audit data with interventions and external factors
 */
export interface TemporalData {
  /** Timestamp of the data point */
  timestamp: Date;
  
  /** URL being analyzed */
  url: string;
  
  /** Scores at this point in time */
  scores: {
    overall: number;
    categories: Record<string, number>;
    citationProbability: number;
  };
  
  /** Interventions applied */
  interventions: {
    type: string;
    description: string;
    implementedAt: Date;
  }[];
  
  /** External factors affecting performance */
  externalFactors: {
    seasonality: number;
    competitorActivity: number;
    algorithmUpdates: string[];
  };
}

// ============================================================================
// Knowledge Graph Types
// ============================================================================

/**
 * Entity types in the knowledge graph
 */
export type EntityType = 
  | 'Person'
  | 'Organization'
  | 'Product'
  | 'Event'
  | 'Place'
  | 'Concept'
  | 'CreativeWork'
  | 'Thing';

/**
 * Entity in the knowledge graph
 */
export interface Entity {
  id: string;
  name: string;
  type: EntityType;
  properties: Record<string, any>;
  mentions: number;
  firstSeen: Date;
  lastSeen: Date;
}

/**
 * Relationship between entities
 */
export interface Relationship {
  id: string;
  sourceId: string;
  targetId: string;
  type: string;
  properties: Record<string, any>;
  strength: number; // 0-1
  confidence: number; // 0-1
}

/**
 * Claim in the knowledge graph
 */
export interface Claim {
  id: string;
  statement: string;
  subjectId: string;
  predicateId: string;
  objectId: string;
  evidence: {
    type: 'citation' | 'data' | 'expert_opinion';
    source: string;
    confidence: number;
  }[];
  temporalScope?: {
    start?: Date;
    end?: Date;
  };
}

/**
 * Complete knowledge graph
 */
export interface KnowledgeGraph {
  entities: Entity[];
  relationships: Relationship[];
  claims: Claim[];
  metadata: {
    sourceUrl: string;
    extractedAt: Date;
    version: string;
  };
}

/**
 * Authority gap between user and competitor
 */
export interface AuthorityGap {
  entity: string;
  userScore: number;
  competitorScore: number;
  gap: number;
  opportunity: 'high' | 'medium' | 'low';
  recommendations: string[];
}

// ============================================================================
// Prediction and Analysis Types
// ============================================================================

/**
 * Feature vector for ML prediction
 */
export interface FeatureVector {
  // Content quality features
  wordCount: number;
  readabilityScore: number;
  semanticDensity: number;
  entityCount: number;
  claimCount: number;
  
  // Entity authority features
  avgEntityAuthority: number;
  maxEntityAuthority: number;
  entityDiversity: number;
  
  // Temporal features
  historicalTrend: number;
  seasonalityIndex: number;
  recentVelocity: number;
  
  // Competitive features
  relativePositioning: number;
  competitiveGapScore: number;
}

/**
 * Explanation of prediction
 */
export interface ExplanationResult {
  score: number;
  topFactors: {
    name: string;
    value: number;
    impact: number;
    explanation: string;
  }[];
  visualizations: {
    type: 'bar' | 'waterfall' | 'radar';
    data: any;
  }[];
}

/**
 * Trend analysis result
 */
export interface TrendAnalysis {
  direction: 'increasing' | 'decreasing' | 'stable';
  slope: number;
  r2: number; // Goodness of fit
  seasonality: {
    detected: boolean;
    period: number; // days
    amplitude: number;
  };
  changePoints: {
    date: Date;
    magnitude: number;
    significance: number;
  }[];
}

/**
 * Anomaly detection result
 */
export interface Anomaly {
  date: Date;
  value: number;
  expected: number;
  deviation: number; // Standard deviations
  severity: 'critical' | 'warning' | 'info';
  possibleCauses: string[];
}

// ============================================================================
// Optimization Types
// ============================================================================

/**
 * Optimization constraints
 */
export interface OptimizationConstraints {
  preserveFactualAccuracy: boolean;
  maintainEEAT: boolean;
  maxLengthIncrease: number; // percentage
  targetAudience: 'technical' | 'general' | 'expert';
}

/**
 * Validation result for content optimization
 */
export interface ValidationResult {
  isValid: boolean;
  factualAccuracyScore: number; // 0-1
  discrepancies: {
    type: 'entity' | 'number' | 'date' | 'quote';
    original: string;
    optimized: string;
    severity: 'critical' | 'warning' | 'info';
  }[];
  eeAtSignals: {
    present: string[];
    missing: string[];
  };
}

/**
 * Strategy recommendation
 */
export interface StrategyRecommendation {
  id: string;
  title: string;
  description: string;
  category: 'content' | 'schema' | 'entity' | 'technical';
  priority: 'high' | 'medium' | 'low';
  expectedImpact: {
    citationLift: number;
    confidence: { lower: number; upper: number };
  };
  effort: {
    level: 'low' | 'medium' | 'high';
    estimatedHours: number;
  };
  implementation: {
    steps: string[];
    resources: string[];
    dependencies: string[];
  };
}

// ============================================================================
// Causal Inference Types
// ============================================================================

/**
 * Intervention tracking
 */
export interface Intervention {
  id: string;
  type: string;
  description: string;
  implementedAt: Date;
  url: string;
  metadata: Record<string, any>;
  status: 'planned' | 'implemented' | 'validated';
}

/**
 * Causal impact analysis result
 */
export interface CausalImpact {
  effect: number; // Average treatment effect
  confidence: { lower: number; upper: number };
  pValue: number;
  significance: boolean;
  counterfactual: number[]; // What would have happened without intervention
}

/**
 * Simulation result for combined interventions
 */
export interface SimulationResult {
  expectedOutcome: number;
  confidence: { lower: number; upper: number };
  contributingInterventions: {
    intervention: string;
    contribution: number;
  }[];
  interactions: {
    interventions: string[];
    synergy: number; // Positive = synergistic, negative = antagonistic
  }[];
}

/**
 * Interaction effect between interventions
 */
export interface InteractionEffect {
  interventions: string[];
  effect: number;
  type: 'synergistic' | 'antagonistic' | 'neutral';
  confidence: number;
}

// ============================================================================
// Model Registry Types
// ============================================================================

/**
 * ML model metadata
 */
export interface CitationProbabilityModel {
  id: string;
  version: string;
  trainedAt: Date;
  features: {
    name: string;
    importance: number;
    type: 'content' | 'entity' | 'temporal' | 'competitive';
  }[];
  performance: {
    precision: number;
    recall: number;
    f1Score: number;
    auc: number;
  };
  hyperparameters: Record<string, any>;
  status: 'active' | 'archived' | 'testing';
}

/**
 * Model version history
 */
export interface ModelVersion {
  modelId: string;
  version: string;
  createdAt: Date;
  createdBy: string;
  changes: string[];
  performanceComparison: {
    previous: number;
    current: number;
    improvement: number;
  };
  rollbackAvailable: boolean;
}

// ============================================================================
// Time Series Types
// ============================================================================

/**
 * Time series data point
 */
export interface TimeSeriesData {
  timestamp: Date;
  value: number;
  metadata?: Record<string, any>;
}

/**
 * Outcome data for causal analysis
 */
export interface OutcomeData {
  interventionId: string;
  metric: string;
  before: TimeSeriesData[];
  after: TimeSeriesData[];
  control?: TimeSeriesData[];
}

// ============================================================================
// Export and Integration Types
// ============================================================================

/**
 * Export format options
 */
export type ExportFormat = 'json' | 'csv' | 'graphml';

/**
 * Export request
 */
export interface ExportRequest {
  format: ExportFormat;
  includeForecasts: boolean;
  includeKnowledgeGraph: boolean;
  includeRecommendations: boolean;
  dateRange?: {
    start: Date;
    end: Date;
  };
}

/**
 * Export result
 */
export interface ExportResult {
  format: ExportFormat;
  data: string | Buffer;
  metadata: {
    exportedAt: Date;
    recordCount: number;
    dataTypes: string[];
  };
  documentation?: string;
}

// ============================================================================
// Competitive Intelligence Types
// ============================================================================

/**
 * Competitor analysis result
 */
export interface CompetitorAnalysis {
  competitorUrl: string;
  citationProbability: number;
  knowledgeGraph: KnowledgeGraph;
  entityAuthorities: EntityAuthority[];
  contentMetrics: {
    wordCount: number;
    semanticDensity: number;
    entityCount: number;
    claimCount: number;
  };
  analyzedAt: Date;
}

/**
 * Competitive gap analysis
 */
export interface CompetitiveGapAnalysis {
  entityGaps: AuthorityGap[];
  contentDepthGaps: {
    topic: string;
    userDepth: number;
    competitorDepth: number;
    gap: number;
  }[];
  citationStrategyGaps: {
    strategy: string;
    userImplementation: number; // 0-1
    competitorImplementation: number; // 0-1
    gap: number;
  }[];
  overallPositioning: {
    rank: number;
    totalCompetitors: number;
    percentile: number;
  };
}

// ============================================================================
// Real-time Analysis Types
// ============================================================================

/**
 * Real-time content analysis result
 */
export interface RealTimeAnalysis {
  semanticDensity: number;
  entities: Entity[];
  claims: Claim[];
  citationPotential: number;
  suggestions: {
    type: 'entity' | 'claim' | 'structure' | 'schema';
    priority: 'high' | 'medium' | 'low';
    description: string;
    implementation: string;
  }[];
  processingTime: number; // milliseconds
}

/**
 * Pre-publication checklist
 */
export interface PrePublicationChecklist {
  items: {
    category: string;
    requirement: string;
    status: 'complete' | 'incomplete' | 'warning';
    details: string;
  }[];
  overallReadiness: number; // 0-100
  criticalIssues: string[];
}

// ============================================================================
// System State Types
// ============================================================================

/**
 * Current system state for simulation
 */
export interface SystemState {
  currentScore: number;
  knowledgeGraph: KnowledgeGraph;
  historicalData: TemporalData[];
  activeInterventions: Intervention[];
  competitorData: CompetitorAnalysis[];
}

/**
 * Partial result when some operations fail
 */
export interface PartialResult<T> {
  completedOperations: string[];
  failedOperations: {
    operation: string;
    error: string;
    suggestedAction: string;
  }[];
  data: Partial<T>;
}
