/**
 * Utility functions for Agent Middleware
 * Provides URL normalization and cryptographic hashing
 */

import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex } from '@noble/hashes/utils.js';

/**
 * Normalizes a URL for consistent cache key generation
 * 
 * Normalization steps:
 * 1. Convert to lowercase (except path)
 * 2. Remove trailing slashes
 * 3. Sort query parameters
 * 4. Remove default ports (80 for HTTP, 443 for HTTPS)
 * 5. Remove fragment identifiers
 * 
 * @param url - The URL to normalize
 * @returns Normalized URL string
 * @throws Error if URL is invalid
 */
export function normalizeUrl(url: string): string {
  try {
    const parsed = new URL(url);
    
    // Normalize protocol to lowercase
    const protocol = parsed.protocol.toLowerCase();
    
    // Normalize hostname to lowercase
    const hostname = parsed.hostname.toLowerCase();
    
    // Remove default ports
    let port = parsed.port;
    if ((protocol === 'http:' && port === '80') || 
        (protocol === 'https:' && port === '443')) {
      port = '';
    }
    
    // Keep path as-is (case-sensitive)
    let pathname = parsed.pathname;
    
    // Remove trailing slash unless it's the root path
    if (pathname.length > 1 && pathname.endsWith('/')) {
      pathname = pathname.slice(0, -1);
    }
    
    // Sort query parameters for consistency
    const searchParams = new URLSearchParams(parsed.search);
    const sortedParams = new URLSearchParams(
      Array.from(searchParams.entries()).sort(([a], [b]) => a.localeCompare(b))
    );
    const search = sortedParams.toString();
    
    // Reconstruct URL without fragment
    let normalized = `${protocol}//${hostname}`;
    if (port) {
      normalized += `:${port}`;
    }
    normalized += pathname;
    if (search) {
      normalized += `?${search}`;
    }
    
    return normalized;
  } catch (error) {
    throw new Error(`Invalid URL: ${url}`);
  }
}

/**
 * Generates a SHA-256 hash of a string
 * 
 * @param input - The string to hash
 * @returns Hexadecimal hash string
 */
export function generateHash(input: string): string {
  const hash = sha256(new TextEncoder().encode(input));
  return bytesToHex(hash);
}

/**
 * Generates a cache key for a URL
 * 
 * The cache key is generated by:
 * 1. Normalizing the URL
 * 2. Computing SHA-256 hash
 * 3. Prefixing with namespace
 * 
 * @param url - The URL to generate a cache key for
 * @returns Cache key string in format "agent:wrap:{hash}"
 */
export function generateCacheKey(url: string): string {
  const normalized = normalizeUrl(url);
  const hash = generateHash(normalized);
  return `agent:wrap:${hash}`;
}

/**
 * Validates if a string is a valid HTTP/HTTPS URL
 * 
 * @param url - The string to validate
 * @returns true if valid, false otherwise
 */
export function isValidUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch {
    return false;
  }
}

/**
 * Extracts the domain from a URL
 * 
 * @param url - The URL to extract domain from
 * @returns Domain string (e.g., "example.com")
 * @throws Error if URL is invalid
 */
export function extractDomain(url: string): string {
  try {
    const parsed = new URL(url);
    return parsed.hostname;
  } catch (error) {
    throw new Error(`Invalid URL: ${url}`);
  }
}
