/**
 * Custom Generators for Blog CMS Property-Based Testing
 * 
 * This module provides fast-check generators for creating realistic
 * blog data that respects database constraints.
 * 
 * @module api/__tests__/blog-generators.ts
 */

import fc from 'fast-check';

/**
 * Generates a valid slug (URL-friendly identifier)
 * - Lowercase letters, numbers, and hyphens only
 * - No leading/trailing hyphens
 * - Length: 3-100 characters
 */
export const slugGenerator = fc
  .string({ minLength: 3, maxLength: 100 })
  .map(s => 
    s.toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/^-+|-+$/g, '')
      .replace(/-+/g, '-')
  )
  .filter(s => s.length >= 3);

/**
 * Generates a valid blog post title
 * - Length: 10-200 characters
 * - Contains alphanumeric characters
 */
export const titleGenerator = fc.string({ 
  minLength: 10, 
  maxLength: 200 
}).filter(s => s.trim().length >= 10);

/**
 * Generates a valid blog post excerpt
 * - Length: 50-500 characters
 * - Contains meaningful content
 */
export const excerptGenerator = fc.string({ 
  minLength: 50, 
  maxLength: 500 
}).filter(s => s.trim().length >= 50);

/**
 * Generates a valid blog post content
 * - Length: 100-10000 characters
 * - Contains meaningful content
 */
export const contentGenerator = fc.string({ 
  minLength: 100, 
  maxLength: 10000 
}).filter(s => s.trim().length >= 100);

/**
 * Generates a valid read time (in minutes)
 * - Range: 1-60 minutes
 */
export const readTimeGenerator = fc.integer({ min: 1, max: 60 });

/**
 * Generates a valid blog post status
 */
export const statusGenerator = fc.constantFrom('draft', 'published', 'archived');

/**
 * Generates a valid author name
 * - Length: 3-100 characters
 */
export const authorNameGenerator = fc.string({ 
  minLength: 3, 
  maxLength: 100 
}).filter(s => s.trim().length >= 3);

/**
 * Generates a valid author bio
 * - Length: 10-1000 characters (optional)
 */
export const authorBioGenerator = fc.option(
  fc.string({ minLength: 10, maxLength: 1000 })
    .filter(s => s.trim().length >= 10),
  { nil: undefined }
);

/**
 * Generates a valid email address
 */
export const emailGenerator = fc.emailAddress();

/**
 * Generates a valid job title
 * - Length: 3-100 characters
 */
export const jobTitleGenerator = fc.option(
  fc.string({ minLength: 3, maxLength: 100 })
    .filter(s => s.trim().length >= 3),
  { nil: undefined }
);

/**
 * Generates an array of expertise areas
 * - 0-10 items
 * - Each item: 3-50 characters
 */
export const expertiseGenerator = fc.array(
  fc.string({ minLength: 3, maxLength: 50 })
    .filter(s => s.trim().length >= 3),
  { minLength: 0, maxLength: 10 }
);

/**
 * Generates a valid category name
 * - Length: 3-100 characters
 */
export const categoryNameGenerator = fc.string({ 
  minLength: 3, 
  maxLength: 100 
}).filter(s => s.trim().length >= 3);

/**
 * Generates a valid category description
 * - Length: 10-500 characters (optional)
 */
export const categoryDescriptionGenerator = fc.option(
  fc.string({ minLength: 10, maxLength: 500 })
    .filter(s => s.trim().length >= 10),
  { nil: undefined }
);

/**
 * Generates a valid display order
 * - Range: 0-1000
 */
export const displayOrderGenerator = fc.integer({ min: 0, max: 1000 });

/**
 * Generates a valid tag name
 * - Length: 2-50 characters
 * - Normalized to lowercase
 */
export const tagNameGenerator = fc.string({ 
  minLength: 2, 
  maxLength: 50 
})
  .filter(s => s.trim().length >= 2)
  .map(s => s.toLowerCase().trim());

/**
 * Generates a valid URL for images
 */
export const imageUrlGenerator = fc.webUrl();

/**
 * Generates a valid meta description
 * - Length: 50-160 characters (SEO best practice)
 */
export const metaDescriptionGenerator = fc.option(
  fc.string({ minLength: 50, maxLength: 160 })
    .filter(s => s.trim().length >= 50),
  { nil: undefined }
);

/**
 * Generates an array of meta keywords
 * - 0-10 keywords
 * - Each keyword: 2-30 characters
 */
export const metaKeywordsGenerator = fc.option(
  fc.array(
    fc.string({ minLength: 2, maxLength: 30 })
      .filter(s => s.trim().length >= 2),
    { minLength: 0, maxLength: 10 }
  ),
  { nil: undefined }
);

/**
 * Generates a valid ISO timestamp
 */
export const timestampGenerator = fc.date({ 
  min: new Date('2020-01-01'), 
  max: new Date('2030-12-31') 
}).map(d => d.toISOString());

/**
 * Generates a complete BlogAuthor object
 * Note: Does not include id, created_at, updated_at (generated by database)
 */
export const blogAuthorGenerator = fc.record({
  slug: slugGenerator,
  name: authorNameGenerator,
  bio: authorBioGenerator,
  image_url: fc.option(imageUrlGenerator, { nil: undefined }),
  email: fc.option(emailGenerator, { nil: undefined }),
  job_title: jobTitleGenerator,
  expertise: fc.option(expertiseGenerator, { nil: undefined }),
  knows_about: fc.option(expertiseGenerator, { nil: undefined }),
});

/**
 * Generates a complete BlogCategory object
 * Note: Does not include id, created_at, updated_at (generated by database)
 */
export const blogCategoryGenerator = fc.record({
  slug: slugGenerator,
  name: categoryNameGenerator,
  description: categoryDescriptionGenerator,
  display_order: displayOrderGenerator,
});

/**
 * Generates a complete BlogTag object
 * Note: Does not include id, created_at (generated by database)
 */
export const blogTagGenerator = fc.record({
  name: tagNameGenerator,
  slug: slugGenerator,
});

/**
 * Generates a complete BlogPost object (without relations)
 * Note: Requires author_id and optionally category_id to be provided
 * Does not include id, created_at, updated_at, deleted_at (managed by database)
 */
export const blogPostGenerator = (authorId: string, categoryId?: string | null) => 
  fc.record({
    slug: slugGenerator,
    title: titleGenerator,
    excerpt: excerptGenerator,
    content: contentGenerator,
    author_id: fc.constant(authorId),
    category_id: fc.constant(categoryId ?? null),
    featured: fc.boolean(),
    status: statusGenerator,
    published_date: fc.option(timestampGenerator, { nil: undefined }),
    modified_date: timestampGenerator,
    read_time: readTimeGenerator,
    meta_description: metaDescriptionGenerator,
    meta_keywords: metaKeywordsGenerator,
    og_image_url: fc.option(imageUrlGenerator, { nil: undefined }),
  });

/**
 * Generates a BlogPost with published status and published_date set
 */
export const publishedBlogPostGenerator = (authorId: string, categoryId?: string | null) =>
  blogPostGenerator(authorId, categoryId).map(post => ({
    ...post,
    status: 'published' as const,
    published_date: post.published_date || new Date().toISOString(),
  }));

/**
 * Generates a BlogPost with draft status
 */
export const draftBlogPostGenerator = (authorId: string, categoryId?: string | null) =>
  blogPostGenerator(authorId, categoryId).map(post => ({
    ...post,
    status: 'draft' as const,
    published_date: undefined,
  }));

/**
 * Generates a BlogPost with archived status
 */
export const archivedBlogPostGenerator = (authorId: string, categoryId?: string | null) =>
  blogPostGenerator(authorId, categoryId).map(post => ({
    ...post,
    status: 'archived' as const,
    published_date: post.published_date || new Date().toISOString(),
  }));

/**
 * Generates pagination parameters
 */
export const paginationGenerator = fc.record({
  page: fc.integer({ min: 1, max: 10 }),
  limit: fc.integer({ min: 1, max: 50 }),
});

/**
 * Generates a unique slug with timestamp to avoid collisions
 */
export const uniqueSlugGenerator = (prefix: string = 'test') =>
  slugGenerator.map(slug => `${prefix}-${Date.now()}-${slug}`);
