/**
 * Centralized metadata utilities for GEO Audit exports
 * Ensures consistent metadata across all export formats
 * 
 * Requirements: 6.1-6.5
 */

import { ExportFormat } from './types';

/**
 * Export metadata that should be included in all exports
 */
export interface ExportMetadataInfo {
  generatedBy: string;
  generatedAt: string; // ISO 8601
  toolVersion: string;
  toolName: string;
  exportFormat: string;
  exportVersion: string;
  schemaVersion?: string; // For structured formats (JSON, XML, YAML)
}

/**
 * Get the current tool version from package.json
 */
export function getToolVersion(): string {
  return '1.0.0'; // This matches package.json version
}

/**
 * Get the tool name
 */
export function getToolName(): string {
  return 'Anóteros Lógos GEO Audit Tool';
}

/**
 * Get the current timestamp in ISO 8601 format
 * Requirement 6.1: ISO 8601 timestamps
 */
export function getCurrentTimestamp(): string {
  return new Date().toISOString();
}

/**
 * Get complete export metadata for a given format
 * Requirements: 6.1, 6.2, 6.5
 */
export function getExportMetadata(format: ExportFormat): ExportMetadataInfo {
  const metadata: ExportMetadataInfo = {
    generatedBy: getToolName(),
    generatedAt: getCurrentTimestamp(),
    toolVersion: getToolVersion(),
    toolName: getToolName(),
    exportFormat: format,
    exportVersion: '1.0.0'
  };

  // Add schema version for structured formats (Requirement 6.5)
  if (isStructuredFormat(format)) {
    metadata.schemaVersion = getSchemaVersion(format);
  }

  return metadata;
}

/**
 * Check if a format is structured (JSON, XML, YAML)
 */
export function isStructuredFormat(format: ExportFormat): boolean {
  return [
    ExportFormat.JSON,
    ExportFormat.XML,
    ExportFormat.YAML
  ].includes(format);
}

/**
 * Get schema version for structured formats
 * Requirement 6.5: Schema version information
 */
export function getSchemaVersion(format: ExportFormat): string {
  switch (format) {
    case ExportFormat.JSON:
      return 'geo-audit-schema-v1.0.0';
    case ExportFormat.XML:
      return 'geo-audit-schema-v1.0.0';
    case ExportFormat.YAML:
      return 'geo-audit-schema-v1.0.0';
    default:
      return 'geo-audit-schema-v1.0.0';
  }
}

/**
 * Format metadata as a human-readable string
 * Used for text-based formats (Markdown, Plain Text, CSV)
 */
export function formatMetadataAsText(metadata: ExportMetadataInfo): string {
  let text = '';
  text += `Generated by: ${metadata.generatedBy}\n`;
  text += `Tool Version: ${metadata.toolVersion}\n`;
  text += `Export Format: ${metadata.exportFormat}\n`;
  text += `Export Version: ${metadata.exportVersion}\n`;
  text += `Generated At: ${metadata.generatedAt}\n`;
  
  if (metadata.schemaVersion) {
    text += `Schema Version: ${metadata.schemaVersion}\n`;
  }
  
  return text;
}

/**
 * Format metadata as JSON object
 * Used for JSON exports
 */
export function formatMetadataAsJSON(metadata: ExportMetadataInfo): Record<string, string> {
  const json: Record<string, string> = {
    generatedBy: metadata.generatedBy,
    toolVersion: metadata.toolVersion,
    exportFormat: metadata.exportFormat,
    exportVersion: metadata.exportVersion,
    generatedAt: metadata.generatedAt
  };
  
  if (metadata.schemaVersion) {
    json.schemaVersion = metadata.schemaVersion;
  }
  
  return json;
}

/**
 * Format metadata as XML elements
 * Used for XML exports
 */
export function formatMetadataAsXML(metadata: ExportMetadataInfo): string {
  let xml = '  <metadata>\n';
  xml += `    <generatedBy>${escapeXML(metadata.generatedBy)}</generatedBy>\n`;
  xml += `    <toolVersion>${escapeXML(metadata.toolVersion)}</toolVersion>\n`;
  xml += `    <exportFormat>${escapeXML(metadata.exportFormat)}</exportFormat>\n`;
  xml += `    <exportVersion>${escapeXML(metadata.exportVersion)}</exportVersion>\n`;
  xml += `    <generatedAt>${escapeXML(metadata.generatedAt)}</generatedAt>\n`;
  
  if (metadata.schemaVersion) {
    xml += `    <schemaVersion>${escapeXML(metadata.schemaVersion)}</schemaVersion>\n`;
  }
  
  xml += '  </metadata>\n';
  return xml;
}

/**
 * Format metadata as YAML
 * Used for YAML exports
 */
export function formatMetadataAsYAML(metadata: ExportMetadataInfo): string {
  let yaml = 'metadata:\n';
  yaml += `  generatedBy: "${metadata.generatedBy}"\n`;
  yaml += `  toolVersion: "${metadata.toolVersion}"\n`;
  yaml += `  exportFormat: "${metadata.exportFormat}"\n`;
  yaml += `  exportVersion: "${metadata.exportVersion}"\n`;
  yaml += `  generatedAt: "${metadata.generatedAt}"\n`;
  
  if (metadata.schemaVersion) {
    yaml += `  schemaVersion: "${metadata.schemaVersion}"\n`;
  }
  
  return yaml;
}

/**
 * Format metadata for PDF/HTML footer
 * Requirement 6.4: Page numbers and generation date for PDF/HTML
 */
export function formatMetadataForFooter(metadata: ExportMetadataInfo, pageNumber?: number): string {
  const date = new Date(metadata.generatedAt).toLocaleDateString();
  let footer = `Generated by ${metadata.generatedBy} | ${date}`;
  
  if (pageNumber !== undefined) {
    footer += ` | Page ${pageNumber}`;
  }
  
  return footer;
}

/**
 * Format metadata for HTML meta tags
 * Requirement 6.4: Metadata in HTML exports
 */
export function formatMetadataAsHTMLMeta(metadata: ExportMetadataInfo): string {
  let html = '';
  html += `  <meta name="generator" content="${escapeHTML(metadata.generatedBy)} v${escapeHTML(metadata.toolVersion)}" />\n`;
  html += `  <meta name="export-format" content="${escapeHTML(metadata.exportFormat)}" />\n`;
  html += `  <meta name="export-version" content="${escapeHTML(metadata.exportVersion)}" />\n`;
  html += `  <meta name="generated-at" content="${escapeHTML(metadata.generatedAt)}" />\n`;
  
  if (metadata.schemaVersion) {
    html += `  <meta name="schema-version" content="${escapeHTML(metadata.schemaVersion)}" />\n`;
  }
  
  return html;
}

/**
 * Escape XML special characters
 */
function escapeXML(str: string): string {
  if (!str) return '';
  
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Escape HTML special characters
 */
function escapeHTML(str: string): string {
  if (!str) return '';
  
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
