/**
 * PDF Report Generator - Hi-End AAA Level
 * Professional PDF reports with charts, branding, recommendations
 * Enhanced for complete data export with table of contents
 * 
 * Requirements: 6.1-6.4 (Metadata and compliance features)
 */

import type { AuditResult } from './geoAuditEnhanced';
import { getExportMetadata, formatMetadataForFooter } from './export/metadata';
import { ExportFormat } from './export/types';

interface PDFReportOptions {
  includeCharts?: boolean;
  includeRecommendations?: boolean;
  includeDetails?: boolean;
  companyName?: string;
  reportDate?: string;
}

interface TOCEntry {
  title: string;
  page: number;
  level: number;
}

export async function generatePDFReport(
  result: AuditResult,
  options: PDFReportOptions = {}
): Promise<void> {
  const {
    includeRecommendations = true,
    includeDetails = true,
    companyName = 'Anóteros Lógos',
    reportDate = new Date().toLocaleDateString(),
  } = options;

  // Get standardized metadata (Requirements 6.1, 6.2, 6.4)
  const metadata = getExportMetadata(ExportFormat.PDF);

  // Dynamic import to avoid ESM issues
  const jsPDF = (await import('jspdf')).default;

  // Initialize PDF (A4 size)
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let yPos = margin;
  
  // Table of contents tracking
  const tocEntries: TOCEntry[] = [];

  // Helper function to add new page
  const addPage = () => {
    pdf.addPage();
    yPos = margin;
    // jsPDF internal API for page count
    const pageCount = (pdf as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
    addFooter(pageCount);
    addHeader(pageCount);
  };
  
  // Header function
  const addHeader = (pageNum: number) => {
    if (pageNum <= 1) return; // Skip header on cover page
    
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text('GEO Audit Report', margin, 10);
    
    const hostname = new URL(result.url).hostname;
    pdf.text(hostname, pageWidth - margin, 10, { align: 'right' });
    
    // Header line
    pdf.setDrawColor(96, 165, 250);
    pdf.setLineWidth(0.2);
    pdf.line(margin, 12, pageWidth - margin, 12);
  };
  
  // Helper to add TOC entry
  const addTOCEntry = (title: string, level: number = 1) => {
    const currentPage = (pdf as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
    tocEntries.push({ title, page: currentPage, level });
  };

  // Helper function to check if we need new page
  const checkPageBreak = (requiredSpace: number) => {
    if (yPos + requiredSpace > pageHeight - margin - 15) {
      addPage();
      return true;
    }
    return false;
  };

  // Footer function (Requirement 6.4: Page numbers and generation date)
  const addFooter = (pageNum: number) => {
    const footerY = pageHeight - 10;
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    
    // Left side: Generator and date
    pdf.text(
      `Generated by ${metadata.generatedBy} v${metadata.toolVersion} | ${reportDate}`,
      margin,
      footerY
    );
    
    // Right side: Page number
    pdf.text(
      `Page ${pageNum}`,
      pageWidth - margin - 15,
      footerY
    );
  };

  // ==================== COVER PAGE ====================
  
  // Background gradient effect (simulated with rectangles)
  pdf.setFillColor(30, 41, 59); // secondary color
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');
  
  // Accent bar
  pdf.setFillColor(59, 130, 246); // primary color
  pdf.rect(0, 0, pageWidth, 5, 'F');

  // Logo/Company name
  pdf.setFontSize(32);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(241, 245, 249); // text color
  pdf.text(companyName, pageWidth / 2, 60, { align: 'center' });

  // Report title
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'normal');
  pdf.text('GEO Audit Report', pageWidth / 2, 80, { align: 'center' });

  // Website URL
  pdf.setFontSize(14);
  pdf.setTextColor(148, 163, 184); // textMuted
  const hostname = new URL(result.url).hostname;
  pdf.text(hostname, pageWidth / 2, 95, { align: 'center' });

  // Overall Score - Large centered
  pdf.setFontSize(72);
  pdf.setFont('helvetica', 'bold');
  const scoreColor = result.overallScore >= 80 ? [16, 185, 129] :
                     result.overallScore >= 60 ? [245, 158, 11] :
                     result.overallScore >= 40 ? [251, 146, 60] :
                     [239, 68, 68];
  pdf.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  pdf.text(result.overallScore.toString(), pageWidth / 2, 140, { align: 'center' });
  
  pdf.setFontSize(16);
  pdf.setTextColor(148, 163, 184);
  pdf.text('/ 100', pageWidth / 2, 155, { align: 'center' });

  // Grade badge
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(241, 245, 249);
  pdf.text(`Grade: ${result.grade}`, pageWidth / 2, 175, { align: 'center' });

  // Timestamp (Requirement 6.1: ISO 8601 timestamp)
  pdf.setFontSize(12);
  pdf.setTextColor(148, 163, 184);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Analysis Date: ${new Date(result.timestamp).toLocaleString()}`, pageWidth / 2, 190, { align: 'center' });
  
  // Metadata info
  pdf.setFontSize(9);
  pdf.text(`Report Generated: ${new Date(metadata.generatedAt).toLocaleString()}`, pageWidth / 2, 197, { align: 'center' });

  // Divider
  pdf.setDrawColor(96, 165, 250);
  pdf.setLineWidth(0.5);
  pdf.line(margin + 30, 200, pageWidth - margin - 30, 200);

  // Report description
  pdf.setFontSize(11);
  pdf.setTextColor(203, 213, 225);
  const description = 'This comprehensive GEO (Generative Engine Optimization) audit analyzes your website\'s\nreadiness for AI-powered search engines and provides actionable recommendations\nto improve visibility in ChatGPT, Perplexity, and other AI platforms.';
  pdf.text(description, pageWidth / 2, 215, { align: 'center', maxWidth: contentWidth - 40 });

  addFooter(1);

  // ==================== TABLE OF CONTENTS ====================
  addPage();
  
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(59, 130, 246);
  pdf.text('Table of Contents', margin, yPos);
  yPos += 15;
  
  // We'll come back to fill this in after generating all pages
  const tocPageNumber = (pdf as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
  
  // ==================== EXECUTIVE SUMMARY PAGE ====================
  addPage();
  addTOCEntry('Executive Summary', 1);

  // Page title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(59, 130, 246);
  pdf.text('Executive Summary', margin, yPos);
  yPos += 15;

  // Key metrics grid
  const metrics = [
    { label: 'Schema Markup', score: result.scores.schemaMarkup },
    { label: 'AI Crawlers', score: result.scores.aiCrawlers },
    { label: 'E-E-A-T', score: result.scores.eeat },
    { label: 'Technical SEO', score: result.scores.technicalSEO },
    { label: 'Content Quality', score: result.scores.contentQuality },
    { label: 'Link Analysis', score: result.scores.linkAnalysis },
  ];

  const boxWidth = (contentWidth - 10) / 2;
  const boxHeight = 25;
  let row = 0;
  let col = 0;

  metrics.forEach((metric) => {
    const x = margin + col * (boxWidth + 5);
    const y = yPos + row * (boxHeight + 5);

    // Box background
    const bgColor = metric.score >= 80 ? [16, 185, 129, 30] :
                    metric.score >= 60 ? [245, 158, 11, 30] :
                    metric.score >= 40 ? [251, 146, 60, 30] :
                    [239, 68, 68, 30];
    pdf.setFillColor(bgColor[0], bgColor[1], bgColor[2]);
    pdf.rect(x, y, boxWidth, boxHeight, 'F');

    // Border
    pdf.setDrawColor(96, 165, 250);
    pdf.setLineWidth(0.3);
    pdf.rect(x, y, boxWidth, boxHeight, 'S');

    // Label
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(203, 213, 225);
    pdf.text(metric.label, x + 5, y + 8);

    // Score
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(metric.score >= 80 ? 16 : metric.score >= 60 ? 245 : metric.score >= 40 ? 251 : 239,
                     metric.score >= 80 ? 185 : metric.score >= 60 ? 158 : metric.score >= 40 ? 146 : 68,
                     metric.score >= 80 ? 129 : metric.score >= 60 ? 11 : metric.score >= 40 ? 60 : 68);
    pdf.text(metric.score.toString(), x + boxWidth - 5, y + 20, { align: 'right' });

    col++;
    if (col >= 2) {
      col = 0;
      row++;
    }
  });

  yPos += row * (boxHeight + 5) + boxHeight + 15;

  // Insights section
  if (result.insights && result.insights.length > 0) {
    checkPageBreak(50);
    
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(59, 130, 246);
    pdf.text('Key Insights', margin, yPos);
    yPos += 10;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(203, 213, 225);

    result.insights.slice(0, 5).forEach((insight) => {
      checkPageBreak(15);
      
      // Bullet point
      pdf.setFillColor(96, 165, 250);
      pdf.circle(margin + 2, yPos - 2, 1, 'F');
      
      const lines = pdf.splitTextToSize(insight, contentWidth - 10);
      pdf.text(lines, margin + 7, yPos);
      yPos += lines.length * 5 + 3;
    });
  }

  // ==================== SCORE BREAKDOWN PAGE ====================
  if (includeDetails) {
    addPage();
    addTOCEntry('Detailed Score Breakdown', 1);

    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(59, 130, 246);
    pdf.text('Detailed Score Breakdown', margin, yPos);
    yPos += 15;

    // Table header
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(148, 163, 184);
    pdf.text('Category', margin, yPos);
    pdf.text('Score', margin + 110, yPos);
    pdf.text('Status', margin + 140, yPos);
    yPos += 7;

    // Line separator
    pdf.setDrawColor(96, 165, 250);
    pdf.setLineWidth(0.3);
    pdf.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 5;

    // Table rows
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(203, 213, 225);

    Object.entries(result.scores).forEach(([category, score]) => {
      checkPageBreak(15);

      // Category name
      const categoryName = category.replace(/([A-Z])/g, ' $1').trim();
      pdf.text(categoryName, margin, yPos);

      // Score with color
      const scoreColor = score >= 80 ? [16, 185, 129] :
                        score >= 60 ? [245, 158, 11] :
                        score >= 40 ? [251, 146, 60] :
                        [239, 68, 68];
      pdf.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
      pdf.setFont('helvetica', 'bold');
      pdf.text(score.toString(), margin + 110, yPos);

      // Status badge
      const status = score >= 80 ? 'Excellent' :
                    score >= 60 ? 'Good' :
                    score >= 40 ? 'Fair' :
                    'Needs Work';
      pdf.setFont('helvetica', 'normal');
      pdf.text(status, margin + 140, yPos);

      // Progress bar
      const barWidth = 40;
      const barHeight = 3;
      const barX = pageWidth - margin - barWidth;
      const barY = yPos - 3;
      
      // Background
      pdf.setFillColor(51, 65, 85);
      pdf.rect(barX, barY, barWidth, barHeight, 'F');
      
      // Progress
      pdf.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2]);
      pdf.rect(barX, barY, (barWidth * score) / 100, barHeight, 'F');

      pdf.setTextColor(203, 213, 225);
      pdf.setFont('helvetica', 'normal');
      yPos += 8;
    });
  }

  // ==================== DETAILED ANALYSIS SECTIONS ====================
  if (includeDetails) {
    // Schema Markup Details
    addPage();
    addTOCEntry('Schema Markup Analysis', 1);
    
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(59, 130, 246);
    pdf.text('Schema Markup Analysis', margin, yPos);
    yPos += 10;
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(203, 213, 225);
    
    if (result.details.schemaMarkup) {
      const schema = result.details.schemaMarkup;
      pdf.text(`Total Schemas: ${schema.totalSchemas}`, margin, yPos);
      yPos += 6;
      pdf.text(`Valid Schemas: ${schema.validSchemas}`, margin, yPos);
      yPos += 6;
      pdf.text(`Has Graph Structure: ${schema.hasGraphStructure ? 'Yes' : 'No'}`, margin, yPos);
      yPos += 10;
      
      if (schema.strengths && schema.strengths.length > 0) {
        pdf.setFont('helvetica', 'bold');
        pdf.text('Strengths:', margin, yPos);
        yPos += 6;
        pdf.setFont('helvetica', 'normal');
        schema.strengths.forEach(strength => {
          checkPageBreak(10);
          pdf.setFillColor(96, 165, 250);
          pdf.circle(margin + 2, yPos - 2, 0.8, 'F');
          const lines = pdf.splitTextToSize(strength, contentWidth - 10);
          pdf.text(lines, margin + 6, yPos);
          yPos += lines.length * 5 + 2;
        });
        yPos += 5;
      }
      
      if (schema.issues && schema.issues.length > 0) {
        checkPageBreak(10);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Issues:', margin, yPos);
        yPos += 6;
        pdf.setFont('helvetica', 'normal');
        schema.issues.forEach(issue => {
          checkPageBreak(10);
          pdf.setFillColor(239, 68, 68);
          pdf.circle(margin + 2, yPos - 2, 0.8, 'F');
          const lines = pdf.splitTextToSize(issue, contentWidth - 10);
          pdf.text(lines, margin + 6, yPos);
          yPos += lines.length * 5 + 2;
        });
      }
    }
    
    // Content Quality Details
    addPage();
    addTOCEntry('Content Quality Analysis', 1);
    
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(59, 130, 246);
    pdf.text('Content Quality Analysis', margin, yPos);
    yPos += 10;
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(203, 213, 225);
    
    if (result.details.contentQuality) {
      const content = result.details.contentQuality;
      pdf.text(`Word Count: ${content.wordCount}`, margin, yPos);
      yPos += 6;
      pdf.text(`Readability Score: ${content.readabilityScore}`, margin, yPos);
      yPos += 6;
      pdf.text(`Paragraph Count: ${content.paragraphCount}`, margin, yPos);
      yPos += 6;
      pdf.text(`Image Count: ${content.imageCount}`, margin, yPos);
      yPos += 6;
      pdf.text(`Video Count: ${content.videoCount}`, margin, yPos);
      yPos += 6;
      pdf.text(`Content Depth: ${content.contentDepth}`, margin, yPos);
      yPos += 10;
      
      if (content.strengths && content.strengths.length > 0) {
        pdf.setFont('helvetica', 'bold');
        pdf.text('Strengths:', margin, yPos);
        yPos += 6;
        pdf.setFont('helvetica', 'normal');
        content.strengths.forEach(strength => {
          checkPageBreak(10);
          pdf.setFillColor(96, 165, 250);
          pdf.circle(margin + 2, yPos - 2, 0.8, 'F');
          const lines = pdf.splitTextToSize(strength, contentWidth - 10);
          pdf.text(lines, margin + 6, yPos);
          yPos += lines.length * 5 + 2;
        });
        yPos += 5;
      }
      
      if (content.issues && content.issues.length > 0) {
        checkPageBreak(10);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Issues:', margin, yPos);
        yPos += 6;
        pdf.setFont('helvetica', 'normal');
        content.issues.forEach(issue => {
          checkPageBreak(10);
          pdf.setFillColor(239, 68, 68);
          pdf.circle(margin + 2, yPos - 2, 0.8, 'F');
          const lines = pdf.splitTextToSize(issue, contentWidth - 10);
          pdf.text(lines, margin + 6, yPos);
          yPos += lines.length * 5 + 2;
        });
      }
    }
    
    // Link Analysis Details
    if (result.details.linkAnalysis) {
      addPage();
      addTOCEntry('Link Analysis', 1);
      
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(59, 130, 246);
      pdf.text('Link Analysis', margin, yPos);
      yPos += 10;
      
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(203, 213, 225);
      
      const links = result.details.linkAnalysis;
      pdf.text(`Total Links: ${links.totalLinks}`, margin, yPos);
      yPos += 6;
      pdf.text(`Internal Links: ${links.internalLinks}`, margin, yPos);
      yPos += 6;
      pdf.text(`External Links: ${links.externalLinks}`, margin, yPos);
      yPos += 6;
      pdf.text(`Nofollow Ratio: ${(links.nofollowRatio * 100).toFixed(1)}%`, margin, yPos);
      yPos += 10;
      
      if (links.strengths && links.strengths.length > 0) {
        pdf.setFont('helvetica', 'bold');
        pdf.text('Strengths:', margin, yPos);
        yPos += 6;
        pdf.setFont('helvetica', 'normal');
        links.strengths.forEach(strength => {
          checkPageBreak(10);
          pdf.setFillColor(96, 165, 250);
          pdf.circle(margin + 2, yPos - 2, 0.8, 'F');
          const lines = pdf.splitTextToSize(strength, contentWidth - 10);
          pdf.text(lines, margin + 6, yPos);
          yPos += lines.length * 5 + 2;
        });
        yPos += 5;
      }
      
      if (links.issues && links.issues.length > 0) {
        checkPageBreak(10);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Issues:', margin, yPos);
        yPos += 6;
        pdf.setFont('helvetica', 'normal');
        links.issues.forEach(issue => {
          checkPageBreak(10);
          pdf.setFillColor(239, 68, 68);
          pdf.circle(margin + 2, yPos - 2, 0.8, 'F');
          const lines = pdf.splitTextToSize(issue, contentWidth - 10);
          pdf.text(lines, margin + 6, yPos);
          yPos += lines.length * 5 + 2;
        });
      }
    }
    
    // Knowledge Graph (if present)
    if (result.knowledgeGraph) {
      addPage();
      addTOCEntry('Knowledge Graph', 1);
      
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(59, 130, 246);
      pdf.text('Knowledge Graph', margin, yPos);
      yPos += 10;
      
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(203, 213, 225);
      
      const kg = result.knowledgeGraph;
      pdf.text(`Entities: ${kg.entities.length}`, margin, yPos);
      yPos += 6;
      pdf.text(`Relationships: ${kg.relationships.length}`, margin, yPos);
      yPos += 6;
      pdf.text(`Claims: ${kg.claims.length}`, margin, yPos);
      yPos += 10;
      
      if (kg.entities.length > 0) {
        pdf.setFont('helvetica', 'bold');
        pdf.text('Top Entities:', margin, yPos);
        yPos += 6;
        pdf.setFont('helvetica', 'normal');
        kg.entities.slice(0, 10).forEach(entity => {
          checkPageBreak(8);
          pdf.text(`• ${entity.name} (${entity.type})`, margin + 3, yPos);
          yPos += 5;
        });
      }
    }
    
    // Browser Metadata (if present)
    if (result.browserMetadata) {
      addPage();
      addTOCEntry('Browser Execution Details', 1);
      
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(59, 130, 246);
      pdf.text('Browser Execution Details', margin, yPos);
      yPos += 10;
      
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(203, 213, 225);
      
      const browser = result.browserMetadata;
      pdf.text(`Used Browser: ${browser.usedBrowser ? 'Yes' : 'No'}`, margin, yPos);
      yPos += 6;
      if (browser.userAgent) {
        const uaLines = pdf.splitTextToSize(`User Agent: ${browser.userAgent}`, contentWidth);
        pdf.text(uaLines, margin, yPos);
        yPos += uaLines.length * 5 + 3;
      }
      if (browser.loadTime) {
        pdf.text(`Load Time: ${browser.loadTime}ms`, margin, yPos);
        yPos += 6;
      }
      if (browser.resourceCounts) {
        pdf.text(`Scripts: ${browser.resourceCounts.scripts}`, margin, yPos);
        yPos += 6;
        pdf.text(`Stylesheets: ${browser.resourceCounts.stylesheets}`, margin, yPos);
        yPos += 6;
        pdf.text(`Images: ${browser.resourceCounts.images}`, margin, yPos);
        yPos += 6;
      }
    }
  }

  // ==================== RECOMMENDATIONS PAGE ====================
  if (includeRecommendations && result.recommendations.length > 0) {
    addPage();
    addTOCEntry('Action Plan & Recommendations', 1);

    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(59, 130, 246);
    pdf.text('Action Plan & Recommendations', margin, yPos);
    yPos += 15;

    // Group by priority
    const critical = result.recommendations.filter(r => r.priority === 'critical');
    const high = result.recommendations.filter(r => r.priority === 'high');
    const medium = result.recommendations.filter(r => r.priority === 'medium');

    const renderRecommendations = (recs: typeof result.recommendations, title: string, color: number[]) => {
      if (recs.length === 0) return;

      checkPageBreak(20);

      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(color[0], color[1], color[2]);
      pdf.text(title, margin, yPos);
      yPos += 8;

      recs.forEach((rec, idx) => {
        checkPageBreak(35);

        // Box for recommendation
        pdf.setDrawColor(96, 165, 250);
        pdf.setLineWidth(0.3);
        pdf.setFillColor(30, 41, 59);
        const boxStartY = yPos;
        
        // Title
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(241, 245, 249);
        pdf.text(`${idx + 1}. ${rec.title}`, margin + 3, yPos + 5);
        yPos += 10;

        // Description
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(203, 213, 225);
        const descLines = pdf.splitTextToSize(rec.description, contentWidth - 10);
        pdf.text(descLines, margin + 3, yPos);
        yPos += descLines.length * 4 + 3;

        // Impact
        if (rec.impact) {
          pdf.setTextColor(148, 163, 184);
          pdf.setFont('helvetica', 'italic');
          const impactLines = pdf.splitTextToSize(`Impact: ${rec.impact}`, contentWidth - 10);
          pdf.text(impactLines, margin + 3, yPos);
          yPos += impactLines.length * 4 + 3;
        }

        // Effort badge
        if (rec.effort) {
          pdf.setFontSize(8);
          pdf.setFont('helvetica', 'bold');
          const effortColor = rec.effort === 'quick-win' ? [16, 185, 129] :
                             rec.effort === 'strategic' ? [59, 130, 246] :
                             [168, 85, 247];
          pdf.setTextColor(effortColor[0], effortColor[1], effortColor[2]);
          pdf.text(`Effort: ${rec.effort.toUpperCase()}`, margin + 3, yPos);
          
          if (rec.estimatedTime) {
            pdf.setTextColor(148, 163, 184);
            pdf.text(`| ${rec.estimatedTime}`, margin + 35, yPos);
          }
          yPos += 5;
        }

        // Draw box
        const boxHeight = yPos - boxStartY;
        pdf.rect(margin, boxStartY - 2, contentWidth, boxHeight, 'S');
        
        yPos += 3;
      });

      yPos += 5;
    };

    if (critical.length > 0) {
      renderRecommendations(critical, '🔴 Critical Priority', [239, 68, 68]);
    }
    if (high.length > 0) {
      renderRecommendations(high, '🟠 High Priority', [245, 158, 11]);
    }
    if (medium.length > 0) {
      renderRecommendations(medium.slice(0, 3), '🟡 Medium Priority (Top 3)', [234, 179, 8]);
    }
  }

  // ==================== FINAL PAGE ====================
  addPage();
  addTOCEntry('Next Steps', 1);

  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(59, 130, 246);
  pdf.text('Next Steps', margin, yPos);
  yPos += 15;

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(203, 213, 225);

  const nextSteps = [
    'Review critical and high-priority recommendations first',
    'Implement quick-win optimizations to see immediate improvements',
    'Schedule strategic implementations with your development team',
    'Re-run this audit after changes to track progress',
    'Monitor your AI citation frequency in ChatGPT and Perplexity',
  ];

  nextSteps.forEach((step, idx) => {
    pdf.setFillColor(96, 165, 250);
    pdf.circle(margin + 2, yPos - 2, 1, 'F');
    const lines = pdf.splitTextToSize(`${idx + 1}. ${step}`, contentWidth - 10);
    pdf.text(lines, margin + 7, yPos);
    yPos += lines.length * 6 + 2;
  });

  yPos += 15;

  // CTA
  pdf.setFillColor(59, 130, 246);
  pdf.roundedRect(margin, yPos, contentWidth, 35, 3, 3, 'F');
  
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(255, 255, 255);
  pdf.text('Need Expert Help?', pageWidth / 2, yPos + 12, { align: 'center' });
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Our GEO specialists can implement these recommendations', pageWidth / 2, yPos + 20, { align: 'center' });
  pdf.text('and maximize your AI visibility.', pageWidth / 2, yPos + 26, { align: 'center' });

  const finalPageCount = (pdf as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
  addFooter(finalPageCount);

  // ==================== FILL IN TABLE OF CONTENTS ====================
  // Go back to TOC page
  pdf.setPage(tocPageNumber);
  yPos = margin + 15;
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(203, 213, 225);
  
  tocEntries.forEach(entry => {
    checkPageBreak(8);
    
    const indent = (entry.level - 1) * 5;
    const titleX = margin + indent;
    const pageX = pageWidth - margin - 10;
    
    // Title
    pdf.text(entry.title, titleX, yPos);
    
    // Dots
    pdf.setTextColor(100, 100, 100);
    const dotsStart = titleX + pdf.getTextWidth(entry.title) + 2;
    const dotsEnd = pageX - 2;
    let dotX = dotsStart;
    while (dotX < dotsEnd) {
      pdf.text('.', dotX, yPos);
      dotX += 2;
    }
    
    // Page number
    pdf.setTextColor(203, 213, 225);
    pdf.text(entry.page.toString(), pageX, yPos, { align: 'right' });
    
    yPos += 6;
  });

  // ==================== SAVE PDF ====================
  const hostnameForFile = new URL(result.url).hostname;
  const fileName = `GEO-Audit-${hostnameForFile}-${Date.now()}.pdf`;
  pdf.save(fileName);
}

// Export for use in components
export default generatePDFReport;
